# Generated by Django 5.1.7 on 2025-03-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0003_rename_active_userprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('hr', 'HR'), ('employee', 'Employee')], default='employee', max_length=10),
        ),
    ]
