# Generated by Django 5.1.7 on 2025-03-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0007_leavetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetable',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
