# Generated by Django 5.1.7 on 2025-03-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0008_rename_employee_leavetable_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
