# Generated by Django 5.1.7 on 2025-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0010_alter_leavetable_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
