# Generated by Django 5.1.7 on 2025-03-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0011_alter_leavetable_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetable',
            name='leave_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
