# Generated by Django 5.1.7 on 2025-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0012_alter_leavetable_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetable',
            name='leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetable',
            name='remaining_leaves',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='leavetable',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
    ]
