# Generated by Django 5.1.7 on 2025-03-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0013_leavetable_leaves_taken_leavetable_remaining_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetable',
            name='leaves_taken',
        ),
        migrations.RemoveField(
            model_name='leavetable',
            name='remaining_leaves',
        ),
        migrations.RemoveField(
            model_name='leavetable',
            name='total_leaves',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remaining_leaves',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_leaves',
            field=models.IntegerField(default=10),
        ),
    ]
