# Generated by Django 5.1.7 on 2025-03-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0014_remove_leavetable_leaves_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='remaining_leaves',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
    ]
