# Generated by Django 5.1.7 on 2025-03-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0015_alter_userprofile_remaining_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leaves_taken',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='remaining_leaves',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_leaves',
        ),
    ]
