# Generated by Django 5.1.7 on 2025-03-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0016_remove_userprofile_leaves_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leaves_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remaining_leaves',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
    ]
