# Generated by Django 5.1.7 on 2025-04-02 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0017_userprofile_leaves_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('Bonus', 'Bonus'), ('Overtime', 'Overtime'), ('Travel', 'Travel'), ('House Rent', 'House Rent'), ('Daily Allowance', 'Daily Allowance')], max_length=20)),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('Tax', 'Tax'), ('Provident Fund', 'Provident Fund'), ('Loan Repayment', 'Loan Repayment'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=20)),
                ('amount', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('net_salary', models.FloatField()),
                ('allowances', models.FloatField(default=0.0)),
                ('deductions', models.FloatField(default=0.0)),
                ('salary_status', models.CharField(choices=[('Pending', 'Pending'), ('paid', 'Paid')], default='Pending', max_length=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
