# Generated by Django 5.1.7 on 2025-04-03 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0018_allowances_deductions_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowances',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deductions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deductions',
            name='deduction_type',
            field=models.CharField(choices=[('TDS', 'Tds'), ('PF', 'Pf'), ('Insurance', 'Insurance'), ('LOP', 'Lop'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
