# Generated by Django 5.1.7 on 2025-04-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paysphere_app', '0019_allowances_created_at_deductions_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='deduction_type',
            field=models.CharField(choices=[('TDS', 'Tax Deducted at Source'), ('PF', 'Provident Fund'), ('INSURANCE', 'Insurance'), ('LOP', 'Loss of Pay'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
